const carnatic_ragas = [
        {
        "name": "Kanakangi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 1,
        "chakra": "Indu",
        "Arohana" : ["S", "R1", "G1", "M1", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R1", "G1", "M1", "P", "D1", "N1", "S"],
        "parent": "none" ,
        },
        {
        "name": "Ratnangi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 2,
        "chakra": "Indu",
        "Arohana" : ["S", "R1", "G1", "M1", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R1", "G1", "M1", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Ganamurti",
        "te_name" : "",
        "type": "Melakarta",
        "number": 3,
        "chakra": "Indu",
        "Arohana" : ["S", "R1", "G1", "M1", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R1", "G1", "M1", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Vanaspati",
        "te_name" : "",
        "type": "Melakarta",
        "number": 4,
        "chakra": "Indu",
        "Arohana" : ["S", "R1", "G1", "M1", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R1", "G1", "M1", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Manavati",
        "te_name" : "",
        "type": "Melakarta",
        "number": 5,
        "chakra": "Indu",
        "Arohana" : ["S", "R1", "G1", "M1", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R1", "G1", "M1", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Tanarupi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 6,
        "chakra": "Indu",
        "Arohana" : ["S", "R1", "G1", "M1", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R1", "G1", "M1", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Senavati",
        "te_name" : "",
        "type": "Melakarta",
        "number": 7,
        "chakra": "Netra",
        "Arohana" : ["S", "R1", "G2", "M1", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R1", "G2", "M1", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Hanumatodi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 8,
        "chakra": "Netra",
        "Arohana" : ["S", "R1", "G2", "M1", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R1", "G2", "M1", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Dhenuka",
        "te_name" : "",
        "type": "Melakarta",
        "number": 9,
        "chakra": "Netra",	 
        "Arohana" : ["S", "R1", "G2", "M1", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R1", "G2", "M1", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Natakapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 10,
        "chakra": "Netra",
        "Arohana" : ["S", "R1", "G2", "M1", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R1", "G2", "M1", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Kokilapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 11,
        "chakra": "Netra",
        "Arohana" : ["S", "R1", "G2", "M1", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R1", "G2", "M1", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Rupavati",
        "te_name" : "",
        "type": "Melakarta",
        "number": 12,
        "chakra": "Netra",
        "Arohana" : ["S", "R1", "G2", "M1", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R1", "G2", "M1", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Gayakapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 13,
        "chakra": "Agni",
        "Arohana" : ["S", "R1", "G3", "M1", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R1", "G3", "M1", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Vakulabharanam",
        "te_name" : "",
        "type": "Melakarta",
        "number": 14,
        "chakra": "Agni",
        "Arohana" : ["S", "R1", "G3", "M1", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R1", "G3", "M1", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Mayamalavagowla",
        "te_name" : "",
        "type": "Melakarta",
        "number": 15,
        "chakra": "Agni",
        "Arohana" : ["S", "R1", "G3", "M1", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R1", "G3", "M1", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Chakravakam",
        "te_name" : "",
        "type": "Melakarta",
        "number": 16,
        "chakra": "Agni",
        "Arohana" : ["S", "R1", "G3", "M1", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R1", "G3", "M1", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Suryakantam",
        "te_name" : "",
        "type": "Melakarta",
        "number": 17,
        "chakra": "Agni",
        "Arohana" : ["S", "R1", "G3", "M1", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R1", "G3", "M1", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Hatakambari",
        "te_name" : "",
        "type": "Melakarta",
        "number": 18,
        "chakra": "Agni",
        "Arohana" : ["S", "R1", "G3", "M1", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R1", "G3", "M1", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Jhankaradhwani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 19,
        "chakra": "Veda",
        "Arohana" : ["S", "R2", "G2", "M1", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R2", "G2", "M1", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Natabhairavi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 20,
        "chakra": "Veda",
        "Arohana" : ["S", "R2", "G2", "M1", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R2", "G2", "M1", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Keeravani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 21,
        "chakra": "Veda",   
        "Arohana" : ["S", "R2", "G2", "M1", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R2", "G2", "M1", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Kharaharapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 22,
        "chakra": "Veda",
        "Arohana" : ["S", "R2", "G2", "M1", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R2", "G2", "M1", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Gourimanohari",
        "te_name" : "",
        "type": "Melakarta",
        "number": 23,
        "chakra": "Veda",
        "Arohana" : ["S", "R2", "G2", "M1", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R2", "G2", "M1", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Varunapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 24,
        "chakra": "Veda", 
        "Arohana" : ["S", "R2", "G2", "M1", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R2", "G2", "M1", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Mararanjani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 25,
        "chakra": "Bana",
        "Arohana" : ["S", "R2", "G3", "M1", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R2", "G3", "M1", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Charukesi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 26,
        "chakra": "Bana",
        "Arohana" : ["S", "R2", "G3", "M1", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R2", "G3", "M1", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Sarasangi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 27,
        "chakra": "Bana",
        "Arohana" : ["S", "R2", "G3", "M1", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R2", "G3", "M1", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Harikambhoji",
        "te_name" : "",
        "type": "Melakarta",
        "number": 28,
        "chakra": "Bana",
        "Arohana" : ["S", "R2", "G3", "M1", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R2", "G3", "M1", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Dheerasankarabharanam",
        "te_name" : "",
        "type": "Melakarta",
        "number": 29,
        "chakra": "Bana",
        "Arohana" : ["S", "R2", "G3", "M1", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R2", "G3", "M1", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Naganandini",
        "te_name" : "",
        "type": "Melakarta",
        "number": 30,
        "chakra": "Bana",
        "Arohana" : ["S", "R2", "G3", "M1", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R2", "G3", "M1", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Yagapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 31,
        "chakra": "Rutu",
        "Arohana" : ["S", "R3", "G3", "M1", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R3", "G3", "M1", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Ragavardhini",
        "te_name" : "",
        "type": "Melakarta",
        "number": 32,
        "chakra": "Rutu",
        "Arohana" : ["S", "R3", "G3", "M1", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R3", "G3", "M1", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Gangeyabhushani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 33,
        "chakra": "Rutu",
        "Arohana" : ["S", "R3", "G3", "M1", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R3", "G3", "M1", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Vagadheeswari",
        "te_name" : "",
        "type": "Melakarta",
        "number": 34,
        "chakra": "Rutu",
        "Arohana" : ["S", "R3", "G3", "M1", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R3", "G3", "M1", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Shulini",
        "te_name" : "",
        "type": "Melakarta",
        "number": 35,
        "chakra": "Rutu",
        "Arohana" : ["S", "R3", "G3", "M1", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R3", "G3", "M1", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Chalanata",
        "te_name" : "",
        "type": "Melakarta",
        "number": 36,
        "chakra": "Rutu",
        "Arohana" : ["S", "R3", "G3", "M1", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R3", "G3", "M1", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Salagam",
        "te_name" : "",
        "type": "Melakarta",
        "number": 37,
        "chakra": "Rishi",
        "Arohana" : ["S", "R1", "G1", "M2", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R1", "G1", "M2", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Jalarnavam",
        "te_name" : "",
        "type": "Melakarta",
        "number": 38,
        "chakra": "Rishi",
        "Arohana" : ["S", "R1", "G1", "M2", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R1", "G1", "M2", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Jhalavarali",
        "te_name" : "",
        "type": "Melakarta",
        "number": 39,
        "chakra": "Rishi",
        "Arohana" : ["S", "R1", "G1", "M2", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R1", "G1", "M2", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Navaneetam",
        "te_name" : "",
        "type": "Melakarta",
        "number": 40,
        "chakra": "Rishi",
        "Arohana" : ["S", "R1", "G1", "M2", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R1", "G1", "M2", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Pavani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 41,
        "chakra": "Rishi",
        "Arohana" : ["S", "R1", "G1", "M2", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R1", "G1", "M2", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Raghupriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 42,
        "chakra": "Rishi",
        "Arohana" : ["S", "R1", "G1", "M2", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R1", "G1", "M2", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Gavambhodi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 43,
        "chakra": "Vasu",
        "Arohana" : ["S", "R1", "G2", "M2", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R1", "G2", "M2", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Bhavapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 44,
        "chakra": "Vasu",
        "Arohana" : ["S", "R1", "G2", "M2", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R1", "G2", "M2", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Shubhapantuvarali",
        "te_name" : "",
        "type": "Melakarta",
        "number": 45,
        "chakra": "Vasu",
        "Arohana" : ["S", "R1", "G2", "M2", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R1", "G2", "M2", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Shadvidamargini",
        "te_name" : "",
        "type": "Melakarta",
        "number": 46,
        "chakra": "Vasu",
        "Arohana" : ["S", "R1", "G2", "M2", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R1", "G2", "M2", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Suvarnangi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 47,
        "chakra": "Vasu",
        "Arohana" : ["S", "R1", "G2", "M2", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R1", "G2", "M2", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Divyamani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 48,
        "chakra": "Vasu",
        "Arohana" : ["S", "R1", "G2", "M2", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R1", "G2", "M2", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Dhavalambari",
        "te_name" : "",
        "type": "Melakarta",
        "number": 49,
        "chakra": "Brahma",
        "Arohana" : ["S", "R1", "G3", "M2", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R1", "G3", "M2", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Namanarayani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 50,
        "chakra": "Brahma",
        "Arohana" : ["S", "R1", "G3", "M2", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R1", "G3", "M2", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Kamavardani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 51,
        "chakra": "Brahma",
        "Arohana" : ["S", "R1", "G3", "M2", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R1", "G3", "M2", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Ramapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 52,
        "chakra": "Brahma",
        "Arohana" : ["S", "R1", "G3", "M2", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R1", "G3", "M2", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Gamanashrama",
        "te_name" : "",
        "type": "Melakarta",
        "number": 53,
        "chakra": "Brahma",
        "Arohana" : ["S", "R1", "G3", "M2", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R1", "G3", "M2", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Vishwambari",
        "te_name" : "",
        "type": "Melakarta",
        "number": 54,
        "chakra": "Brahma",
        "Arohana" : ["S", "R1", "G3", "M2", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R1", "G3", "M2", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Shamalangi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 55,
        "chakra": "Disi",
        "Arohana" : ["S", "R2", "G2", "M2", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R2", "G2", "M2", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Shanmukhapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 56,
        "chakra": "Disi",
        "Arohana" : ["S", "R2", "G2", "M2", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R2", "G2", "M2", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Simhendramadhyamam",
        "te_name" : "",
        "type": "Melakarta",
        "number": 57,
        "chakra": "Disi",
        "Arohana" : ["S", "R2", "G2", "M2", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R2", "G2", "M2", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Hemavati",
        "te_name" : "",
        "type": "Melakarta",
        "number": 58,
        "chakra": "Disi",
        "Arohana" : ["S", "R2", "G2", "M2", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R2", "G2", "M2", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Dharmavati",
        "te_name" : "",
        "type": "Melakarta",
        "number": 59,
        "chakra": "Disi",
        "Arohana" : ["S", "R2", "G2", "M2", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R2", "G2", "M2", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Neetimati",
        "te_name" : "",
        "type": "Melakarta",
        "number": 60,
        "chakra": "Disi",
        "Arohana" : ["S", "R2", "G2", "M2", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R2", "G2", "M2", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Kantamani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 61,
        "chakra": "Rudra",
        "Arohana" : ["S", "R2", "G3", "M2", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R2", "G3", "M2", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Rishabhapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 62,
        "chakra": "Rudra",
        "Arohana" : ["S", "R2", "G3", "M2", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R2", "G3", "M2", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Latangi",
        "te_name" : "",
        "type": "Melakarta",
        "number": 63,
        "chakra": "Rudra",
        "Arohana" : ["S", "R2", "G3", "M2", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R2", "G3", "M2", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Vachaspati",
        "te_name" : "",
        "type": "Melakarta",
        "number": 64,
        "chakra": "Rudra",
        "Arohana" : ["S", "R2", "G3", "M2", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R2", "G3", "M2", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "kalyani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 65,
        "chakra": "Rudra",
        "Arohana" : ["S", "R2", "G3", "M2", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R2", "G3", "M2", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Chitrambari",
        "te_name" : "",
        "type": "Melakarta",
        "number": 66,
        "chakra": "Rudra",
        "Arohana" : ["S", "R2", "G3", "M2", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R2", "G3", "M2", "P", "D3", "N3", "S"],
        "parent": "none" 
        },
        {

        "name": "Sucharitra",
        "te_name" : "",
        "type": "Melakarta",
        "number": 67,
        "chakra": "Aditya",
        "Arohana" : ["S", "R3", "G3", "M2", "P", "D1", "N1", "S"],
        "Avarohana" : ["S", "R3", "G3", "M2", "P", "D1", "N1", "S"],
        "parent": "none" 
        },
        {
        "name": "Jyoti sarupini",
        "te_name" : "",
        "type": "Melakarta",
        "number": 68,
        "chakra": "Aditya",	
        "Arohana" : ["S", "R3", "G3", "M2", "P", "D1", "N2", "S"],
        "Avarohana" : ["S", "R3", "G3", "M2", "P", "D1", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Dhatuvardani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 69,
        "chakra": "Aditya",	
        "Arohana" : ["S", "R3", "G3", "M2", "P", "D1", "N3", "S"],
        "Avarohana" : ["S", "R3", "G3", "M2", "P", "D1", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Nasikabhushani",
        "te_name" : "",
        "type": "Melakarta",
        "number": 70,
        "chakra": "Aditya",
        "Arohana" : ["S", "R3", "G3", "M2", "P", "D2", "N2", "S"],
        "Avarohana" : ["S", "R3", "G3", "M2", "P", "D2", "N2", "S"],
        "parent": "none" 
        },
        {
        "name": "Kosalam",
        "te_name" : "",
        "type": "Melakarta",
        "number": 71,
        "chakra": "Aditya",
        "Arohana" : ["S", "R3", "G3", "M2", "P", "D2", "N3", "S"],
        "Avarohana" : ["S", "R3", "G3", "M2", "P", "D2", "N3", "S"],
        "parent": "none" 
        },
        {
        "name": "Rasikapriya",
        "te_name" : "",
        "type": "Melakarta",
        "number": 72,
        "chakra": "Aditya",
        "Arohana" : ["S", "R3", "G3", "M2", "P", "D3", "N3", "S"],
        "Avarohana" : ["S", "R3", "G3", "M2", "P", "D3", "N3", "S"],
        "parent": "none" },
        {
        "name": "Madhyamavathi",
        "te_name" : "",
        "type": "Janya",
        "number": 73,
        "chakra": "Veda",
        "Arohana" : ["S", "R2", "M1", "P", "N2", "S"],
        "Avarohana" : ["S", "R2", "M1", "P", "N2", "S"],
        "parent": "Kharaharapriya" },
        {
        "name": "Kapi",
        "te_name" : "",
        "type": "Janya",
        "number": 74,
        "chakra": "Veda",
        "Arohana" : ["S", "R2", "M1", "P", "N3", "S"],
        "Avarohana" : ["S", "R2", "G2", "M1", "P", "N2", "D2", "N2", "S"],
        "parent": "Kharaharapriya" },
        {
        "name": "Mohanam",
        "te_name" : "",
        "type": "Janya",
        "number": 75,
        "chakra": "Bana",
        "Arohana" : ["S", "R2", "G3", "P", "D2", "S"],
        "Avarohana" : ["S", "R2", "G3", "P", "D2", "S"],
        "parent": "Harikambhoji" },
        {
        "name": "Sivaranjani",
        "te_name" : "",
        "type": "Janya",
        "number": 76,
        "chakra": "Veda",
        "Arohana" : ["S", "R2", "G2", "P", "D2", "S"],
        "Avarohana" : ["S", "R2", "G2", "P", "D2", "S"],
        "parent": "Kharaharapriya" },
        {
        "name": "Abheri",
        "te_name" : "",
        "type": "Janya",
        "number": 77,
        "chakra": "Veda",
        "Arohana" : ["S", "G2", "M1", "P", "N2", "S"],
        "Avarohana" : ["S", "R2", "G2", "M1", "P", "D2", "N2", "S"],
        "parent": "Kharaharapriya" },
        {
        "name": "Hamsadhwani",
        "te_name" : "",
        "type": "Janya",
        "number": 78,
        "chakra": "Bana",
        "Arohana" : ["S", "R2", "G3", "P", "N3", "S"],
        "Avarohana" : ["S", "R2", "G3", "P", "N3", "S"],
        "parent": "Dheerasankarabharanam" },
        {
        "name": "Revathi",
        "te_name" : "",
        "type": "Janya",
        "number": 79,
        "chakra": "Indu",
        "Arohana" : ["S", "R1", "M1", "P", "N2", "S"],
        "Avarohana" : ["S", "R1", "M1", "P", "N2", "S"],
        "parent": "Ratnangi" },
        {
        "name": "Hindolam",
        "te_name" : "",
        "type": "Janya",
        "number": 79,
        "chakra": "Veda",
        "Arohana" : ["S", "G2", "M1", "D1", "N2", "S"],
        "Avarohana" : ["S", "G2", "M1", "D1", "N2", "S"],
        "parent": "Natabhairavi" },
        {
        "name": "Abhogi",
        "te_name" : "",
        "type": "Janya",
        "number": 80,
        "chakra": "Veda",
        "Arohana" : ["S", "R2", "G2", "M1", "D2", "S"],
        "Avarohana" : ["S", "R2", "G2", "M1", "D2", "S"],
        "parent": "Kharaharapriya" },
        {
        "name": "Yadukula Kambhoji",
        "te_name" : "",
        "type": "Janya",
        "number": 81,
        "chakra": "Bana",
        "Arohana" : ["S", "R2", "M1", "P", "D2", "S"],
        "Avarohana" : ["S","R2","G3","M1","P","D2","N2","S"],
        "parent": "Harikambhoji" },
        {
        "name": "Suddha Dhanyasi",
        "te_name" : "",
        "type": "Janya",
        "number": 82,
        "chakra": "Veda",
        "Arohana" : ["S","G2", "M1", "P", "N2", "S"],
        "Avarohana" : ["S","G2", "M1", "P", "N2", "S"],
        "parent": "Kharaharapriya" },
        {
        "name": "Sama",
        "te_name" : "",
        "type": "Janya",
        "number": 83,
        "chakra": "Bana",
        "Arohana" : ["S","R2", "M1", "P", "D2", "S"],
        "Avarohana" : ["S","R2", "G3", "M1", "P", "D2", "S"],
        "parent": "Harikambhoji" },
        {
        "name": "Bhimplas",
        "te_name" : "",
        "type": "Janya",
        "number": 84,
        "chakra": "Veda",
        "Arohana" : ["S", "G2", "M1", "P", "N2", "S"],
        "Avarohana" : ["S", "R2", "G2", "M1", "P", "D2", "N2", "S"],
        "parent": "Kharaharapriya" },
        {
        "name": "Bowli",
        "te_name" : "",
        "type": "Janya",
        "number": 85,
        "chakra": "Agni",
        "Arohana" : ["S", "R1", "G3", "P", "D1", "S"],
        "Avarohana" : ["S", "R1", "G3", "P", "D1", "N3", "S"],
        "parent": "Mayamalavagowla" },
        {
        "name": "Bhupalam or Bhoopalam",
        "te_name" : "",
        "type": "Janya",
        "number": 86,
        "chakra": "Netra",
        "Arohana" : ["S", "R1", "G2", "P", "D1", "S"],
        "Avarohana" : ["S", "R1", "G2", "P", "D1", "S"],
        "parent": "Hanumatodi" },
        {
        "name": "Revagupti or Regupti",
        "te_name" : "",
        "type": "Janya",
        "number": 87,
        "chakra": "Agni",
        "Arohana" : ["S", "R1", "G3", "P", "D1", "S"],
        "Avarohana" : ["S", "R1", "G3", "P", "D1", "S"],
        "parent": "Mayamalavagowla" },
        {
        "name": "Shri or shree",
        "te_name" : "",
        "type": "Janya",
        "number": 88,
        "chakra": "Veda",
        "Arohana" : ["S", "R2", "M1", "P", "N2", "S"],
        "Avarohana" : ["S", "N2", "P", "D2", "N2", "P", "M1", "R2", "G2", "R2", "S"],
        "parent": "Kharaharapriya" },
        {
        "name": "Ahiri",
        "te_name": "",
        "type": "Janya",
        "number": 89,
        "chakra": "Agni",
        "Arohana": ["S","R1","S","G3","M1","P","D1","N2","S"],
        "Avarohana": ["S","R1","G3","M1","P","D1","N2","S"],
        "parent": "Vakulabaranam"
        },
        {
        "name": "Amrithavarshini",
        "te_name": "",
        "type": "Janya",
        "number": 90,
        "chakra": "",
        "Arohana": ["S","G3","M2","P","N3","S"],
        "Avarohana": ["S","G3","M2","P","N3","S"],
        "parent": "Chithrambari"},
        {
        "name": "Ananda Bhairavi",
        "te_name": "",
        "type": "Janya",
        "number": 91,
        "chakra": "Veda",
        "Arohana": ["S","G2","R2","G2","M1","P","D2","P","S"],
        "Avarohana": ["S","R2","G2","M1","P","D2","N2","S"],
        "parent": "Natabhairavi"},
        {
        "name": "Andolika",
        "te_name": "",
        "type": "Janya",
        "number": 92,
        "chakra": "Veda",
        "Arohana": ["S","R2","M1","P","N2","S"],
        "Avarohana": ["S","R2","M1","D2","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Arabhi",
        "te_name": "",
        "type": "Janya",
        "number": 93,
        "chakra": "",
        "Arohana": ["S","R2","M1","P","D2","S"],
        "Avarohana": ["S","R2","G3","M1","P","D2","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Asaveri",
        "te_name": "",
        "type": "Janya",
        "number": 94,
        "chakra": "Netra",
        "Arohana": ["S","R1","M1","P","D1","S"],
        "Avarohana": ["S","R1","G2","M1","P","D1","P","S","N2","S"],
        "parent": "Hanumatodi"},
        {
        "name": "Atana",
        "te_name": "",
        "type": "Janya",
        "number": 95,
        "chakra": "",
        "Arohana": ["S","R2","M1","P","N3","S"],
        "Avarohana": ["S","R2","G3","R2","M1","P","D2","S","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Bageshri",
        "te_name": "",
        "type": "Janya",
        "number": 96,
        "chakra": "Veda",
        "Arohana": ["S","G2","M1","D2","N2","S"],
        "Avarohana": ["S","R2","M1","G2","P","M1","D2","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Bahudari",
        "te_name": "",
        "type": "Janya",
        "number": 97,
        "chakra": "",
        "Arohana": ["S","G3","M1","P","D2","N2","S"],
        "Avarohana": ["S","G3","M1","P","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Begada",
        "te_name": "",
        "type": "Janya",
        "number": 98,
        "chakra": "",
        "Arohana": ["S","G3","R2","G3","M1","P","D2","P","S"],
        "Avarohana": ["R2","G3","M1","P","D2","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Behag",
        "te_name": "",
        "type": "Janya",
        "number": 99,
        "chakra": "",
        "Arohana": ["S","G3","M1","P","N3","D2","N3","S"],
        "Avarohana": ["S","R2","G3","M1","G3","M2","P","D2","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Bhairavi",
        "te_name": "",
        "type": "Janya",
        "number": 100,
        "chakra": "Veda",
        "Arohana": ["S","G2","R2","G2","M1","P","D2","N2","S"],
        "Avarohana": ["S","R2","G2","M1","P","D1","N2","S"],
        "parent": "Natabhairavi"},
        {
        "name": "Bilahari",
        "te_name": "",
        "type": "Janya",
        "number": 101,
        "chakra": "",
        "Arohana": ["S","R2","G3","P","D2","S"],
        "Avarohana": ["S","R2","G3","M1","P","D2","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Brindavana Saranga",
        "te_name": "",
        "type": "Janya",
        "number": 102,
        "chakra": "Veda",
        "Arohana": ["S","R2","M1","P","N3","S"],
        "Avarohana": ["S","G2","R2","M1","P","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Chandrajyoti",
        "te_name": "",
        "type": "Janya",
        "number": 103,
        "chakra": "Rishi",
        "Arohana": ["S","R1","G1","M2","P","D2","S"],
        "Avarohana": ["S","R1","G1","M2","P","D2","S"],
        "parent": "Pavani"},
        {
        "name": "Chandrakauns",
        "te_name": "",
        "type": "Janya",
        "number": 104,
        "chakra": "Veda",
        "Arohana": ["S","G2","M1","D1","N3","S"],
        "Avarohana": ["S","G2","M1","D1","N3","S"],
        "parent": "Keeravani"},
        {
        "name": "Darbar",
        "te_name": "",
        "type": "Janya",
        "number": 105,
        "chakra": "Veda",
        "Arohana": ["S","R2","M1","P","D2","N2","S"],
        "Avarohana": ["S","R2","G2","G2","R2","M1","P","D2","S","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Darbari Kanada",
        "te_name": "",
        "type": "Janya",
        "number": 106,
        "chakra": "Veda",
        "Arohana": ["S","R2","G2","M1","P","D1","N2","S"],
        "Avarohana": ["S","R2","M1","G2","P","M1","P","N2","D1","S"],
        "parent": "Natabhairavi"},
        {
        "name": "Desh",
        "te_name": "",
        "type": "Janya",
        "number": 107,
        "chakra": "",
        "Arohana": ["S","R2","M1","P","N3","S"],
        "Avarohana": ["S","R2","G3","M1","P","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Deva Manohari",
        "te_name": "",
        "type": "Janya",
        "number": 108,
        "chakra": "Veda",
        "Arohana": ["S","R2","M1","P","D2","N2","S"],
        "Avarohana": ["S","R2","M1","P","N2","D2","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Devagandhari",
        "te_name": "",
        "type": "Janya",
        "number": 109,
        "chakra": "",
        "Arohana": ["S","R2","M1","P","D2","S"],
        "Avarohana": ["S","R2","G3","M1","P","D2","N2","D2","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Dhanyasi",
        "te_name": "",
        "type": "Janya",
        "number": 110,
        "chakra": "",
        "Arohana": ["S","G2","M1","P","N2","S"],
        "Avarohana": ["S","R1","G2","M1","P","D1","N2","S"],
        "parent": "Thodi"},
        {
        "name": "Dwijavanti",
        "te_name": "",
        "type": "Janya",
        "number": 111,
        "chakra": "",
        "Arohana": ["S","R2","G3","M1","P","D2","S"],
        "Avarohana": ["S","R2","G2","R2","M1","G3","M1","P","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Gambheera Nattai",
        "te_name": "",
        "type": "Janya",
        "number": 112,
        "chakra": "",
        "Arohana": ["S","G3","M1","P","N3","S"],
        "Avarohana": ["S","G3","M1","P","N3","S"],
        "parent": "Chala Nattai"},
        {
        "name": "Gowlai",
        "te_name": "",
        "type": "Janya",
        "number": 113,
        "chakra": "",
        "Arohana": ["S","R1","M1","P","N3","S"],
        "Avarohana": ["S","R1","M1","G3","R1","M1","G3","M1","P","N3","S"],
        "parent": "Mayamalavagowlai"},
        {
        "name": "Hamir Kalyani",
        "te_name": "",
        "type": "Janya",
        "number": 114,
        "chakra": "",
        "Arohana": ["S","P","M2","P","D2","N3","S"],
        "Avarohana": ["S","R2","M1","P","G3","M1","M2","P","D2","N3","S"],
        "parent": "Kalyani"},
        {
        "name": "Hamsanadam",
        "te_name": "",
        "type": "Janya",
        "number": 115,
        "chakra": "",
        "Arohana": ["S","R2","M2","P","N3","S"],
        "Avarohana": ["S","R2","M2","P","N3","S"],
        "parent": "Neethimathi"},
        {
        "name": "Hamsanandi",
        "te_name": "",
        "type": "Janya",
        "number": 116,
        "chakra": "Brahma",
        "Arohana": ["S","R1","G3","M2","D2","N3","S"],
        "Avarohana": ["S","R1","G3","M2","D2","N3","S"],
        "parent": "Gamanashrama"},
        {
        "name": "Huseni",
        "te_name": "",
        "type": "Janya",
        "number": 117,
        "chakra": "Veda",
        "Arohana": ["S","R2","G2","M1","P","N2","D2","N2","S"],
        "Avarohana": ["S","R2","G2","M1","P","D1","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Jaganmohini",
        "te_name": "",
        "type": "Janya",
        "number": 118,
        "chakra": "",
        "Arohana": ["S","G3","M1","P","N3","S"],
        "Avarohana": ["S","R1","G3","M1","P","N3","S"],
        "parent": "Mayamalavagowlai"},
        {
        "name": "Janaranjani",
        "te_name": "",
        "type": "Janya",
        "number": 119,
        "chakra": "",
        "Arohana": ["S","R2","G3","M1","P","D2","P","N3","S"],
        "Avarohana": ["S","R2","M1","P","D2","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Jayanthashri",
        "te_name": "",
        "type": "Janya",
        "number": 120,
        "chakra": "Veda",
        "Arohana": ["S","G2","M1","D1","N2","S"],
        "Avarohana": ["S","G2","M1","P","M1","D1","N2","S"],
        "parent": "Natabhairavi"},
        {
        "name": "Kadanakuthoohalam",
        "te_name": "",
        "type": "Janya",
        "number": 121,
        "chakra": "",
        "Arohana": ["S","R2","M1","D2","N3","G3","P","S"],
        "Avarohana": ["S","R2","G3","M1","P","D2","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Kalavati",
        "te_name": "",
        "type": "Janya",
        "number": 122,
        "chakra": "Agni",
        "Arohana": ["S","R1","M1","P","D2","S"],
        "Avarohana": ["S","D2","R1","S","G3","M1","P","D2","S"],
        "parent": "Chakravakam"},
        {
        "name": "Kalyana Vasantham",
        "te_name": "",
        "type": "Janya",
        "number": 123,
        "chakra": "Veda",
        "Arohana": ["S","G2","M1","D1","N3","S"],
        "Avarohana": ["S","R2","G2","M1","P","D1","N3","S"],
        "parent": "Keeravani"},
        {
        "name": "Kamala Manohari",
        "te_name": "",
        "type": "Janya",
        "number": 124,
        "chakra": "Bana",
        "Arohana": ["S","G3","M1","P","N3","S"],
        "Avarohana": ["S","G3","M1","P","D1","N3","S"],
        "parent": "Sarasangi"},
        {
        "name": "Kambhoji",
        "te_name": "",
        "type": "Janya",
        "number": 125,
        "chakra": "",
        "Arohana": ["S","R2","G3","M1","P","D2","S"],
        "Avarohana": ["S","R2","G3","M1","P","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Kanada",
        "te_name": "",
        "type": "Janya",
        "number": 126,
        "chakra": "Veda",
        "Arohana": ["S","R2","P","G2","M1","D2","N2","S"],
        "Avarohana": ["S","R2","M1","G2","M1","P","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Kannada",
        "te_name": "",
        "type": "Janya",
        "number": 127,
        "chakra": "",
        "Arohana": ["S","G3","M1","P","M1","D2","N3","S"],
        "Avarohana": ["S","R2","M1","G3","M1","P","D2","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Kannada Gowlai",
        "te_name": "",
        "type": "Janya",
        "number": 128,
        "chakra": "Veda",
        "Arohana": ["S","R2","G2","M1","P","N2","S"],
        "Avarohana": ["S","G2","M1","P","D2","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Kapi",
        "te_name": "",
        "type": "Janya",
        "number": 129,
        "chakra": "Veda",
        "Arohana": ["S","R2","M1","P","N3","S"],
        "Avarohana": ["S","R2","G2","M1","P","N2","D2","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Karna Ranjani",
        "te_name": "",
        "type": "Janya",
        "number": 130,
        "chakra": "Veda",
        "Arohana": ["S","R2","G2","M1","G2","P","D2","S"],
        "Avarohana": ["S","R2","G2","M1","P","D2","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Kedara Gowlai",
        "te_name": "",
        "type": "Janya",
        "number": 131,
        "chakra": "",
        "Arohana": ["S","R2","M1","P","N2","S"],
        "Avarohana": ["S","R2","G3","M1","P","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Kedaram",
        "te_name": "",
        "type": "Janya",
        "number": 132,
        "chakra": "",
        "Arohana": ["S","M1","G3","M1","P","N3","S"],
        "Avarohana": ["S","R2","G3","M1","P","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Khamas",
        "te_name": "",
        "type": "Janya",
        "number": 133,
        "chakra": "",
        "Arohana": ["S","M1","G3","M1","P","D2","N2","S"],
        "Avarohana": ["S","R2","G3","M1","P","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Kuntalavarali",
        "te_name": "",
        "type": "Janya",
        "number": 134,
        "chakra": "",
        "Arohana": ["S","M1","P","D2","N2","D2","S"],
        "Avarohana": ["S","M1","P","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Kuntalavarali",
        "te_name": "",
        "type": "Janya",
        "number": 135,
        "chakra": "",
        "Arohana": ["S","M1","P","D2","N2","D2","S"],
        "Avarohana": ["S","M1","P","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Lalitha",
        "te_name": "",
        "type": "Janya",
        "number": 136,
        "chakra": "",
        "Arohana": ["S","R1","G3","M1","D1","N3","S"],
        "Avarohana": ["S","R1","G3","M1","D1","N3","S"],
        "parent": "Mayamalavagowlai"},
        {
        "name": "Maand",
        "te_name": "",
        "type": "Janya",
        "number": 137,
        "chakra": "",
        "Arohana": ["S","G3","M1","D2","N3","S"],
        "Avarohana": ["S","R2","G3","M1","P","D2","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Madhuvanti",
        "te_name": "",
        "type": "Janya",
        "number": 138,
        "chakra": "Disi",
        "Arohana": ["S","G2","M2","P","N3","S"],
        "Avarohana": ["S","R2","G2","M2","P","D2","N3","S"],
        "parent": "Dharmavati"},
        {
        "name": "Malahari",
        "te_name": "",
        "type": "Janya",
        "number": 139,
        "chakra": "",
        "Arohana": ["S","R1","M1","P","D1","S"],
        "Avarohana": ["S","R1","G3","M1","P","D1","S"],
        "parent": "Mayamalavagowlai"},
        {
        "name": "Malayamarutham",
        "te_name": "",
        "type": "Janya",
        "number": 140,
        "chakra": "Agni",
        "Arohana": ["S","R1","G3","P","D2","N2","S"],
        "Avarohana": ["S","R1","G3","P","D2","N2","S"],
        "parent": "Chakravakam"},
        {
        "name": "Mandari",
        "te_name": "",
        "type": "Janya",
        "number": 141,
        "chakra": "",
        "Arohana": ["S","R1","G3","M2","P","N3","S"],
        "Avarohana": ["S","R1","G3","M2","P","N3","S"],
        "parent": "Kamavardhini"},
        {
        "name": "Manirangu",
        "te_name": "",
        "type": "Janya",
        "number": 142,
        "chakra": "Veda",
        "Arohana": ["S","R2","M1","P","N2","S"],
        "Avarohana": ["S","R2","G2","M1","P","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Mohana Kalyani",
        "te_name": "",
        "type": "Janya",
        "number": 143,
        "chakra": "",
        "Arohana": ["S","R2","G3","P","D2","S"],
        "Avarohana": ["S","R2","G3","M2","P","D2","N3","S"],
        "parent": "Kalyani"},
        {
        "name": "Mukhari",
        "te_name": "",
        "type": "Janya",
        "number": 144,
        "chakra": "Veda",
        "Arohana": ["S","R2","M1","P","N2","D2","S"],
        "Avarohana": ["S","R2","G2","M1","P","D1","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Mukhari",
        "te_name": "",
        "type": "Janya",
        "number": 145,
        "chakra": "Veda",
        "Arohana": ["S","R2","M1","P","N2","D2","S"],
        "Avarohana": ["S","R2","G2","M1","P","D1","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Nagaswarali",
        "te_name": "",
        "type": "Janya",
        "number": 146,
        "chakra": "",
        "Arohana": ["S","G3","M1","P","D2","S"],
        "Avarohana": ["S","G3","M1","P","D2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Nalinakanthi",
        "te_name": "",
        "type": "Janya",
        "number": 147,
        "chakra": "Bana",
        "Arohana": ["S","G3","R2","M1","P","N3","S"],
        "Avarohana": ["S","R2","G3","M1","P","N3","S"],
        "parent": "Sarasangi"},
        {
        "name": "Nattai",
        "te_name": "",
        "type": "Janya",
        "number": 148,
        "chakra": "",
        "Arohana": ["S","R3","G3","M1","P","D3","N3","S"],
        "Avarohana": ["S","R3","M1","G3","M1","P","N3","S"],
        "parent": "Chala Nattai"},
        {
        "name": "Nattai Kurinji",
        "te_name": "",
        "type": "Janya",
        "number": 149,
        "chakra": "",
        "Arohana": ["S","R2","G3","M1","N2","D2","N2","P","D2","N2","S"],
        "Avarohana": ["S","R2","G3","P","M1","G3","M1","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Navarasa Kanada",
        "te_name": "",
        "type": "Janya",
        "number": 150,
        "chakra": "",
        "Arohana": ["S","G3","M1","P","S"],
        "Avarohana": ["S","R2","G3","M1","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Nayaki",
        "te_name": "",
        "type": "Janya",
        "number": 151,
        "chakra": "Veda",
        "Arohana": ["S","R2","M1","P","D2","N2","D2","P","S"],
        "Avarohana": ["S","R2","G2","R2","M1","P","D2","N2","D2","P","S","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Neelambari",
        "te_name": "",
        "type": "Janya",
        "number": 152,
        "chakra": "",
        "Arohana": ["S","G3","M1","P","N3","S"],
        "Avarohana": ["S","G3","M1","R2","G3","M1","P","N2","D2","P","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Poornachandrika",
        "te_name": "",
        "type": "Janya",
        "number": 153,
        "chakra": "",
        "Arohana": ["S","R2","G3","M1","P","D2","P","S"],
        "Avarohana": ["S","R2","M1","G3","R2","M1","P","N3","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Poorvikalyani",
        "te_name": "",
        "type": "Janya",
        "number": 154,
        "chakra": "Brahma",
        "Arohana": ["S","R1","G3","M2","P","D2","P","S"],
        "Avarohana": ["S","R1","G3","M2","P","D2","N3","S"],
        "parent": "Gamanashrama"},
        {
        "name": "Poorvikalyani",
        "te_name": "",
        "type": "Janya",
        "number": 155,
        "chakra": "Brahma",
        "Arohana": ["S","R1","G3","M2","P","D2","P","S"],
        "Avarohana": ["S","R1","G3","M2","P","D2","N3","S"],
        "parent": "Gamanashrama"},
        {
        "name": "Ranjani",
        "te_name": "",
        "type": "Janya",
        "number": 156,
        "chakra": "Disi",
        "Arohana": ["S","R2","G2","M2","D2","S"],
        "Avarohana": ["S","G2","R2","S","G2","M2","D2","N3","S"],
        "parent": "Dharmavati"},
        {
        "name": "Rathipathipriya",
        "te_name": "",
        "type": "Janya",
        "number": 157,
        "chakra": "Veda",
        "Arohana": ["S","R2","G2","P","N2","S"],
        "Avarohana": ["S","R2","G2","P","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Reethigowlai",
        "te_name": "",
        "type": "Janya",
        "number": 158,
        "chakra": "Veda",
        "Arohana": ["S","G2","R2","G2","M1","N2","N2","S"],
        "Avarohana": ["S","R2","G2","M1","P","M1","G2","M1","D2","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Sahana",
        "te_name": "",
        "type": "Janya",
        "number": 159,
        "chakra": "",
        "Arohana": ["S","R2","G3","M1","P","M1","D2","N2","S"],
        "Avarohana": ["S","R2","G3","R2","M1","G3","M1","P","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Saramati",
        "te_name": "",
        "type": "Janya",
        "number": 160,
        "chakra": "Veda",
        "Arohana": ["S","R2","G2","M1","P","D1","N2","S"],
        "Avarohana": ["S","G2","M1","D1","N2","S"],
        "parent": "Natabhairavi"},
        {
        "name": "Saranga",
        "te_name": "",
        "type": "Janya",
        "number": 161,
        "chakra": "",
        "Arohana": ["S","P","M2","P","D2","N3","S"],
        "Avarohana": ["S","R2","M1","G3","R2","M2","P","D2","S"],
        "parent": "Kalyani"},
        {
        "name": "Saraswathi",
        "te_name": "",
        "type": "Janya",
        "number": 162,
        "chakra": "Rudra",
        "Arohana": ["S","R2","M2","P","D2","S"],
        "Avarohana": ["S","R2","M2","P","D2","N2","S"],
        "parent": "Vachaspati"},
        {
        "name": "Saveri",
        "te_name": "",
        "type": "Janya",
        "number": 163,
        "chakra": "",
        "Arohana": ["S","R1","M1","P","D1","S"],
        "Avarohana": ["S","R1","G3","M1","P","D1","N3","S"],
        "parent": "Mayamalavagowlai"},
        {
        "name": "Saveri",
        "te_name": "",
        "type": "Janya",
        "number": 164,
        "chakra": "",
        "Arohana": ["S","R1","M1","P","D1","S"],
        "Avarohana": ["S","R1","G3","M1","P","D1","N3","S"],
        "parent": "Mayamalavagowlai"},
        {
        "name": "Sindhu Bhairavi",
        "te_name": "",
        "type": "Janya",
        "number": 165,
        "chakra": "Netra",
        "Arohana": ["S","R1","G2","M1","P","D1","N2","S"],
        "Avarohana": ["S","R1","G2","M1","P","D1","N2","S"],
        "parent": "Hanumatodi"},
        {
        "name": "Sowrashtram",
        "te_name": "",
        "type": "Janya",
        "number": 166,
        "chakra": "",
        "Arohana": ["S","R1","G3","M1","P","M1","D2","N3","S"],
        "Avarohana": ["S","R1","G3","M1","P","D2","N2","D2","N3","S"],
        "parent": "Suryakantham"},
        {
        "name": "Sriranjani",
        "te_name": "",
        "type": "Janya",
        "number": 167,
        "chakra": "Veda",
        "Arohana": ["S","R2","G2","M1","D2","N2","S"],
        "Avarohana": ["S","R2","G2","M1","D2","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Suddha Saveri",
        "te_name": "",
        "type": "Janya",
        "number": 168,
        "chakra": "",
        "Arohana": ["S","R2","M1","P","D2","S"],
        "Avarohana": ["S","R2","M1","P","D2","S"],
        "parent": "Shankarabaranam"},
        {
        "name": "Sumanesaranjani",
        "te_name": "",
        "type": "Janya",
        "number": 169,
        "chakra": "Disi",
        "Arohana": ["S","G2","M2","P","N2","S"],
        "Avarohana": ["S","G2","M2","P","N2","S"],
        "parent": "Shanmukhapriya"},
        {
        "name": "Sunadavinodini",
        "te_name": "",
        "type": "Janya",
        "number": 170,
        "chakra": "",
        "Arohana": ["S","G3","M2","D2","N3","S"],
        "Avarohana": ["S","G3","M2","D2","N3","S"],
        "parent": "Kalyani"},
        {
        "name": "Surutti",
        "te_name": "",
        "type": "Janya",
        "number": 171,
        "chakra": "",
        "Arohana": ["S","R2","M1","P","N2","D2","N2","S"],
        "Avarohana": ["S","R2","M1","P","G3","M1","P","D2","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Surya",
        "te_name": "",
        "type": "Janya",
        "number": 172,
        "chakra": "Agni",
        "Arohana": ["S","G3","M1","D1","N2","S"],
        "Avarohana": ["S","G3","M1","D1","N2","S"],
        "parent": "Vakulabaranam"},
        {
        "name": "Thilang",
        "te_name": "",
        "type": "Janya",
        "number": 173,
        "chakra": "",
        "Arohana": ["S","G3","M1","P","N3","S"],
        "Avarohana": ["S","G3","M1","P","N2","S"],
        "parent": "Hari Kambhoji"},
        {
        "name": "Valaji",
        "te_name": "",
        "type": "Janya",
        "number": 174,
        "chakra": "Agni",
        "Arohana": ["S","G3","P","D2","N2","S"],
        "Avarohana": ["S","G3","P","D2","N2","S"],
        "parent": "Chakravakam"},
        {
        "name": "Varali",
        "te_name": "",
        "type": "Janya",
        "number": 175,
        "chakra": "Rishi",
        "Arohana": ["S","G1","R1","G1","M2","P","D1","N3","S"],
        "Avarohana": ["S","R1","G1","M2","P","D1","N3","S"],
        "parent": "Jhalavarali"},
        {
        "name": "Varamu",
        "te_name": "",
        "type": "Janya",
        "number": 176,
        "chakra": "Veda",
        "Arohana": ["S","G2","M1","D2","N2","S"],
        "Avarohana": ["S","G2","M1","D2","N2","S"],
        "parent": "Karaharapriya"},
        {
        "name": "Vasantha",
        "te_name": "",
        "type": "Janya",
        "number": 177,
        "chakra": "",
        "Arohana": ["S","M1","G3","M1","D2","N3","S"],
        "Avarohana": ["S","R1","G3","M1","D2","N3","S"],
        "parent": "Suryakantham"},
        {
        "name": "Vasanthi",
        "te_name": "",
        "type": "Janya",
        "number": 178,
        "chakra": "Bana",
        "Arohana": ["S","R2","G3","P","D1","S"],
        "Avarohana": ["S","R2","G3","P","D1","S"],
        "parent": "Sarasangi"},
        {
        "name": "Vijayanagari",
        "te_name": "",
        "type": "Janya",
        "number": 179,
        "chakra": "Disi",
        "Arohana": ["S","R2","G2","M2","P","D2","S"],
        "Avarohana": ["S","R2","G2","M2","P","D2","S"],
        "parent": "Dharmavati"},
        {
        "name": "Yadukula Kambhoji",
        "te_name": "",
        "type": "Janya",
        "number": 180,
        "chakra": "",
        "Arohana": ["S","R2","M1","P","D2","S"],
        "Avarohana": ["S","R2","G3","M1","P","D2","N2","S"],
        "parent": "Hari Kambhoji"}
        
]
