const raga_songs = {
    "Mayamalavagowla" :["Maapaapala tholaginchu deepalu neeve veliginchinavaiah"],
    "Abheri" : ["Kannulato chusedee guruva kanulaku sonthamavuna","Telavarademo swami nee thalapula munakalo","Janani sivakamini jaya subhakarini", "Nee leela padedha deva."],
    "Kanakangi" : [],
    "Ratnangi" : [],
    "Ganamurti" : [],
    "Vanaspati" : [],
    "Manavati" : [],
    "Tanarupi" : [],
    "Senavati" : [],
    "Hanumatodi" : [],
    "Dhenuka" : [],
    "Natakapriya" : [],
    "Kokilapriya" : [],
    "Rupavati" : [],
    "Gayakapriya" : [],
    "Vakulabharanam" : [],
    "Chakravakam" : [],
    "Suryakantam" : [],
    "Hatakambari" : [],
    "Jhankaradhwani" : [],
    "Natabhairavi" : ["Gajulamma gaajulu",],
    "Keeravani" : [],
    "Kharaharapriya" : [],
    "Gourimanohari" : [],
    "Varunapriya" : [],
    "Mararanjani" : [],
    "Charukesi" : [],
    "Sarasangi" : [],
    "Harikambhoji" : [],
    "Dheerasankarabharanam" : ["Narayana mantram sriman narayana mantram", "Garuda gamana tava"],
    "Naganandini" : [],
    "Yagapriya" : [],
    "Ragavardhini" : [],
    "Gangeyabhushani" : [],
    "Vagadheeswari" : [],
    "Shulini" : [],
    "Chalanata" : [],
    "Salagam" : [],
    "Jalarnavam" : [],
    "Jhalavarali" : [],
    "Navaneetam" : [],
    "Pavani" : [],
    "Raghupriya" : [],
    "Gavambhodi" : [],
    "Bhavapriya" : [],
    "Shubhapantuvarali" : [],
    "Shadvidamargini" : [],
    "Suvarnangi" : [],
    "Divyamani" : [],
    "Dhavalambari" : [],
    "Namanarayani" : [],
    "Kamavardani" : [],
    "Ramapriya" : [],
    "Gamanashrama" : [],
    "Vishwambari" : [],
    "Shamalangi" : [],
    "Shanmukhapriya" : [],
    "Simhendramadhyamam" : [],
    "Hemavati" : [],
    "Dharmavati" : [],
    "Neetimati" : [],
    "Kantamani" : [],
    "Rishabhapriya" : [],
    "Latangi" : [],
    "Vachaspati" : [],
    "Mechakalyani" : [],
    "Chitrambari" : [],
    "Sucharitra" : [],
    "Jyoti sarupini" : [],
    "Dhatuvardani" : [],
    "Nasikabhushani" : [],
    "Kosalam" : [],
    "Rasikapriya" : [],
    "Madhyamavathi" : ["sankara nadha sarirapara"],
    "Kapi" : ["Madhava kesava madhusudana vishnu"],
    "Mohanam" : ["siva siva shankara bhakthava shankara","Veyyi vela gopemala muvva gopalude", "Manasu parimalinchene", "Ghana gana sundara karuna rasa mandhira", "Jaya krishnamukunda murari"],
    "Sivaranjani" : ["Evariki Evarayya Eshwara", "Andamina vennelalona acha telugu paduchuvale"],
    "Hansadhwani" : ["suklam baradaram", "vaathapi gana pathim baje"],
    "Revathi" : ["subhakarudu suruchirudu bhavaharudu bhagavanthudevadu"],
    "Hindolam" : ["Pagale venela jagame vuyala kadile vuhaleke kannulunte..", "Nigama nigamanthavr nithamano hara rupa"],
    "Kalyni" : ["Jaya krishnamukunda murari"],
    "Abhogi" : ["kontha kalam kontha kalam, kalamagi povali"],
    "Sriranjani" :[],
    "Suddha Dhanyasi" : ["Bale manchi roju", "Andari bandhuvaya badrachala ramayya"],
    "Sama" : ["Namo venkatesha namo tirumalesha"],
    "Shree" : ["tiruveedula merase deva devudu"],
    "Bowli" : [""],
    "Hindolavasantham": ["Jagadapu chanavula"]
}
